### ISSUE TITLE
Some hotspot data not available on map

### ISSUE THREAD

**Issue by PaulVMo** [helium/cargo-elixir#24]
Not all hotspots are being fetched by the MapScreen. This means the mouseover feature which draws a line from a packet to the hotspot that received it does not work for all hotspots. It looks like only 10,000 hotspots are loaded out of the current 15,000+ per this code. 
https://github.com/helium/cargo-elixir/blob/adc92d58efa896e1418af951b6080e290f029a2a/assets/js/pages/MapScreen.js#L153

This is a nice to have issue and by no means critical functionality. If the limit of 10,000 is intentional, perhaps the list of hotspots can be filtered based on the current view of the map instead of pulling from all hotspots which returns the most recent 10,000 regardless of whether they are on the map or no.

**Comment by kent-williams** [comment]
Thanks for pointing this out @PaulVMo!
